# -*- coding: utf-8 -*-
"""CIS 450/550 Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fIyuqMqijGQ4f-U6KBzF8zQv49FRgEGO
"""

import numpy as np
import pandas as pd
from google.colab import drive
from google.colab import files

prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

"""# data cleaning

"""

investment_path = '/content/drive/My Drive/cis450/investments.csv'
milestone_path = '/content/drive/My Drive/cis450/milestones.csv'
people_path = '/content/drive/My Drive/cis450/people.csv'
ipos_path = '/content/drive/My Drive/cis450/ipos.csv'
relationships_path = '/content/drive/My Drive/cis450/relationships.csv'
object_path = '/content/drive/My Drive/cis450/CIS_550_Project/cleaned_files/objects.csv'


funding_round_path = '/content/drive/My Drive/cis450/CIS_550_Project/cleaned_files/funding_rounds.csv'
acquisitios_path = '/content/drive/My Drive/cis450/CIS_550_Project/cleaned_files/acquisitions.csv'
funds_path = '/content/drive/My Drive/cis450/CIS_550_Project/cleaned_files/funds.csv'
degree_path = '/content/drive/My Drive/cis450/CIS_550_Project/cleaned_files/degree.csv'

investments = pd.read_csv(investment_path)
milestones = pd.read_csv(milestone_path)
people = pd.read_csv(people_path)
relationships = pd.read_csv(relationships_path)
ipos = pd.read_csv(ipos_path)
obj = pd.read_csv(object_path)
funds = pd.read_csv(funds_path)
founding_round = pd.read_csv(funding_round_path)
acquisition = pd.read_csv(acquisitions)

investments = investments.dropna()
milestones = milestones.dropna()
relationships = relationships.dropna()
ipos = ipos.dropna()

investments = investments.drop(columns=['created_at'])

ipos = ipos[ipos.valuation_currency_code=='USD']

ipos = ipos[ipos.raised_currency_code=='USD']

ipos = ipos.drop(columns=['created_at', 'updated_at'])

ipos = ipos.drop(columns=['raised_currency_code', 'valuation_currency_code'])

milestones = milestones.drop(columns=['created_at', 'updated_at'])

milestones = milestones.drop(columns=['milestone_code'])

relationships = relationships.drop(columns=['created_at'])

people.birthplace.fillna("unknown", inplace = True)

relationships.to_csv("relationships.csv", index=False)
milestones.to_csv("milestones.csv", index=False)
ipos.to_csv("ipos.csv", index=False)
investments.to_csv("investments.csv", index=False)

files.download('relationships.csv')

files.download('milestones.csv')
files.download('ipos.csv')
files.download('investments.csv')

people.to_csv("people.csv", index=False)

milestones.head(5)

people.head(5)

relationships.head(5)

ipos.head(5)

investments.head(5)

aq_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/acquisitions.csv'
dg_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/degrees.csv'
fround_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/funding_rounds.csv'
fund_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/funds.csv'
object_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/objects.csv'
ipo_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/ipos.csv'
mi_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/milestones.csv'

aq = pd.read_csv(aq_path)
dg = pd.read_csv(dg_path)
fround = pd.read_csv(fround_path)
fund = pd.read_csv(fund_path)
obj = pd.read_csv(object_path)



aq = aq.dropna()
fround = fround.dropna()
fund = fund.dropna()

aq = aq[aq.price_currency_code=='USD']
fround = fround[fround.raised_currency_code=='USD']
fround = fround[fround.pre_money_currency_code=='USD']
fround = fround[fround.post_money_currency_code=='USD']
fund = fund[fund.raised_currency_code=='USD']

aq = aq.drop(columns=['created_at', 'updated_at','price_currency_code'])
dg = dg.drop(columns=['created_at', 'updated_at'])
fround = fround.drop(columns=['created_at','updated_at','raised_currency_code','pre_money_currency_code','post_money_currency_code',
            'post_money_valuation_usd','pre_money_valuation_usd'])
fund = fund.drop(columns=['created_at', 'updated_at', 'raised_currency_code'])
obj = obj.drop(columns=['created_at', 'updated_at','parent_id','logo_width','logo_height']) # delete parent_id since it's mostly null

dg.fillna("unknown", inplace = True)

aq.head()

dg.head()

fround.head()

fund.head()

obj.head()

aq.to_csv("acquisitions.csv", index=False)
dg.to_csv("degrees.csv", index=False)
fround.to_csv("funding_rounds.csv", index=False)
fund.to_csv("funds.csv", index=False)
obj.to_csv("objects.csv", index=False)

files.download('acquisitions.csv')
files.download('degrees.csv')
files.download('funding_rounds.csv')
files.download('funds.csv')
files.download('objects.csv')

FinOrg.to_csv("FinOrg.csv", index=False)
company.to_csv("company.csv", index=False)
ipos.to_csv("ipos.csv", index=False)
closed.to_csv("closed.csv", index=False)
operating.to_csv("operating.csv", index=False)
acquired.to_csv("acquired.csv", index=False)
milestones.to_csv("milestones.csv", index=False)

files.download('FinOrg.csv')
files.download('company.csv')
files.download('ipos.csv')
files.download('closed.csv')
files.download('operating.csv')
files.download('acquired.csv')
files.download('milestones.csv')

FinOrg.to_csv("FinOrg.csv", index=False)
acquired.to_csv("Acquired.csv", index=False)
files.download('FinOrg.csv')
files.download('Acquired.csv')

#new plan keeps finOrg and fund; compute sum amount during queries
finOrg = obj[obj.entity_type=='FinancialOrg']
finOrg = finOrg[['id', 'name', 'normalized_name', 'founded_at']]
fund = fund[['object_id', 'id', 'name', 'funded_at', 'raised_amount', 'source_url']]
fund.rename(columns={'object_id':'f_id','raised_amount':'amount','source_url':'source'}, inplace=True)

finOrg.to_csv("finOrg.csv", index=False)
fund.to_csv("fund.csv", index=False)

files.download('finOrg.csv')
files.download('fund.csv')

"""# conform tables"""

from google.colab import drive
drive.mount('/content/drive')

company = obj[obj.entity_type=='Company']
person = obj[obj.entity_type=='Person']
acquired = company[company.status=='acquired']
closed = company[company.status=='closed']
operating = company[company.status=='operating']

company.rename(columns={'founded_at':'found_date'}, inplace=True)
company.rename(columns={'category_code':'industry'}, inplace=True)
company = company[['id','name','normalized_name','industry','found_date']]

company.head()

closed.rename(columns={'id':'c_id'}, inplace=True)
closed = closed[['c_id']]

operating.rename(columns={'id':'c_id'}, inplace=True)
operating = operating[['c_id']]

acquired.rename(columns={'id':'c_id'}, inplace=True)
acquired = pd.merge(acquired, aq,left_on='c_id', right_on='acquired_object_id')
acquired.rename(columns={'acquired_object_id':'acquired_id','acquiring_object_id':'acquiring_id'}, inplace=True)
acquired = acquired[['acquired_id','acquiring_id','price_amount']]

ipo_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/ipos.csv'
mi_path = '/content/drive/My Drive/CIS_550_Project/cleaned_files/milestones.csv'
ipos = pd.read_csv(ipo_path)
milestones= pd.read_csv(mi_path)

ipos.rename(columns={'public_at':'ipo_date','object_id':'c_id','valuation_amount':'val_amount'}, inplace=True)
ipos = ipos[['c_id','ipo_id','val_amount','raised_amount','ipo_date','stock_symbol']]

milestones.rename(columns={'milestone_at':'date','object_id':'c_id','source_url':'source'}, inplace=True)
milestones = milestones[['c_id','id','date','description','source']]

milestones.head()

FinOrg = pd.merge(obj,fund[['object_id','funded_at','raised_amount']],left_on='id',right_on='object_id')
FinOrg['size'] = FinOrg.groupby(['object_id'])['raised_amount'].sum()
FinOrg = FinOrg.drop(columns=['object_id'])
FinOrg = FinOrg[['id','name','normalized_name','funded_at','size']]

FinOrg.head()